Fix log stream prefix not found
fluent-plugins-nursery/fluent-plugin-cloudwatch-logs pull request #218
Opened 2021-01-13 10:06 UTC by minh-nguyenquang

2021-01-13 10:10 UTC, PhanQ approved these changes

2021-01-14 02:31 UTC, cosmo0920 requested changes

2021-01-14 02:31 UTC, cosmo0920 commented on fluent-plugin-cloudwatch-logs.gemspec
> +  spec.add_dependency 'fluentd', '>= 1.12.0'
This patch does not use newer Fluentd feature.
So, you should stay on Fluentd 1.8.0.

2021-01-14 02:41 UTC, cosmo0920 approved these changes

2021-01-14 02:41 UTC, cosmo0920 commented
Looks reasonable change. Thanks for your work!

2021-01-14 02:42 UTC, merged